# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a70a87c4891087024da9ebb3b04b62048ecab0cd524cfb7ab6084e63f82553271886c3bb9b4dad856409b3313e8a177e131d1fcd9a12a095bb5e6fcfadbe8575

test:
  secret_key_base: c2d2e4fdb9b43db45e6c86a56034a4ae5419b93caa5550df32f67d0c8788449fa78578a29c944760dfaa5bb0e96a10992f21a3d968903d0220a648305a38c7b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
